import { NextRequest, NextResponse } from "next/server";
import { adminDb } from "../../../../lib/firebaseAdmin";
import { consumeEnrollToken } from "../../../../lib/agentAuth";

export const dynamic = "force-dynamic";

/**
 * One-time agent enrollment: the pairing token (generated by an admin in the
 * provider panel, 24h TTL, single use) IS the authentication. In exchange the
 * agent receives its permanent identity + bearer key for /api/agent/poll and
 * /api/agent/respond.
 */

// Enrollment is rare and attacker-guessing is pointless (256-bit tokens), but
// don't be an unmetered oracle either.
const WINDOW_MS = 5 * 60 * 1000;
const MAX_ATTEMPTS_PER_WINDOW = 20;
let attempts: number[] = [];

export async function POST(request: NextRequest) {
  const now = Date.now();
  attempts = attempts.filter((t) => now - t < WINDOW_MS);
  if (attempts.length >= MAX_ATTEMPTS_PER_WINDOW) {
    return NextResponse.json({ error: "rate_limited" }, { status: 429 });
  }
  attempts.push(now);

  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid_json" }, { status: 400 });
  }

  const token = typeof body.enroll_token === "string" ? body.enroll_token : "";
  if (!token || token.length < 16) {
    return NextResponse.json({ error: "missing_enroll_token" }, { status: 400 });
  }

  const result = await consumeEnrollToken(token, {
    name: typeof body.name === "string" ? body.name : "",
    agentVersion: typeof body.agent_version === "string" ? body.agent_version : "",
    platform: typeof body.platform === "string" ? body.platform : "",
    lookupMode: typeof body.lookup_mode === "string" ? body.lookup_mode : "",
  });

  if ("error" in result) {
    const status = result.error === "database_unavailable" ? 503 : 401;
    return NextResponse.json({ error: result.error }, { status });
  }

  let providerName = "";
  if (adminDb) {
    const provider = await adminDb.collection("venue_api_providers").doc(result.providerId).get();
    providerName = provider.data()?.name || "";
  }

  // The agent stores these in its credentials file; the key never crosses again.
  return NextResponse.json({
    agent_id: result.agentId,
    agent_key: result.agentKey,
    provider_id: result.providerId,
    provider_name: providerName,
  });
}
